const data =[
    {
        id: 1,
        name: 'Lenovo Wireless Mouse',
        category: 'accesories',
        brand: 'Lenovo',
        price: 65,
        description: 'The Lenovo 300 Wireless Compact Mouse is designed to offer the best balance between mobility and function. The mouse features a 1000 dpi sensor, 3 buttons and a unique ergonomic contour to give you the freedom to create whenever and wherever. It boasts a 12-month battery life from a single AA battery and 10 million clicks lifecycle buttons to offer Super portable design.',
        img: 'https://p1-ofp.static.pub/ShareResource/560x450/SSNP/GX30K79402/GX30K79402-560x450-03.49fa2a7b001e506a.png',
        sale: false,
        sellCount: 15,
    },
    {
        id: 2,
        name: 'Hp Wireless Mouse',
        category: 'accesories',
        brand: 'Hp',
        price: 35,
        description: 'The Lenovo 300 Wireless Compact Mouse is designed to offer the best balance between mobility and function. The mouse features a 1000 dpi sensor, 3 buttons and a unique ergonomic contour to give you the freedom to create whenever and wherever. It boasts a 12-month battery life from a single AA battery and 10 million clicks lifecycle buttons to offer Super portable design.',
        img: 'https://p1-ofp.static.pub/ShareResource/560x450/SSNP/GX30K79402/GX30K79402-560x450-03.49fa2a7b001e506a.png',
        sale: true,
        sellCount: 15,
    },
    {
        id: 3,
        name: 'Acer all iin one laptop',
        category: 'laptops',
        brand: 'acer',
        price: 65,
        description: 'The Lenovo 300 Wireless Compact Mouse is designed to offer the best balance between mobility and function. The mouse features a 1000 dpi sensor, 3 buttons and a unique ergonomic contour to give you the freedom to create whenever and wherever. It boasts a 12-month battery life from a single AA battery and 10 million clicks lifecycle buttons to offer Super portable design.',
        img: 'https://p1-ofp.static.pub/ShareResource/560x450/SSNP/GX30K79402/GX30K79402-560x450-03.49fa2a7b001e506a.png',
        sale: false,
        sellCount: 15,
    },
    {
        id: 4,
        name: 'Lenovo Wireless Mouse',
        category: 'accesories',
        brand: 'Lenovo',
        price: 12,
        description: 'The Lenovo 300 Wireless Compact Mouse is designed to offer the best balance between mobility and function. The mouse features a 1000 dpi sensor, 3 buttons and a unique ergonomic contour to give you the freedom to create whenever and wherever. It boasts a 12-month battery life from a single AA battery and 10 million clicks lifecycle buttons to offer Super portable design.',
        img: 'https://p1-ofp.static.pub/ShareResource/560x450/SSNP/GX30K79402/GX30K79402-560x450-03.49fa2a7b001e506a.png',
        sale: true,
        sellCount: 15,
    },
    {
        id: 5,
        name: 'Lenovo Wireless Mouse',
        category: 'accesories',
        brand: 'Lenovo',
        price: 15,
        description: 'The Lenovo 300 Wireless Compact Mouse is designed to offer the best balance between mobility and function. The mouse features a 1000 dpi sensor, 3 buttons and a unique ergonomic contour to give you the freedom to create whenever and wherever. It boasts a 12-month battery life from a single AA battery and 10 million clicks lifecycle buttons to offer Super portable design.',
        img: 'https://p1-ofp.static.pub/ShareResource/560x450/SSNP/GX30K79402/GX30K79402-560x450-03.49fa2a7b001e506a.png',
        sale: false,
        sellCount: 15,
    },
    {
        id: 6,
        name: 'Samsung Galaxy Tab 10.3',
        category: 'tablets',
        brand: 'Samsung',
        price: 729,
        description: 'The Lenovo 300 Wireless Compact Mouse is designed to offer the best balance between mobility and function. The mouse features a 1000 dpi sensor, 3 buttons and a unique ergonomic contour to give you the freedom to create whenever and wherever. It boasts a 12-month battery life from a single AA battery and 10 million clicks lifecycle buttons to offer Super portable design.',
        img: 'https://p1-ofp.static.pub/ShareResource/560x450/SSNP/GX30K79402/GX30K79402-560x450-03.49fa2a7b001e506a.png',
        sale: true,
        sellCount: 15,
    },
    {
        id: 7,
        name: 'Lenovo Wireless Mouse',
        category: 'accesories',
        brand: 'Lenovo',
        price: 65,
        description: 'The Lenovo 300 Wireless Compact Mouse is designed to offer the best balance between mobility and function. The mouse features a 1000 dpi sensor, 3 buttons and a unique ergonomic contour to give you the freedom to create whenever and wherever. It boasts a 12-month battery life from a single AA battery and 10 million clicks lifecycle buttons to offer Super portable design.',
        img: 'https://p1-ofp.static.pub/ShareResource/560x450/SSNP/GX30K79402/GX30K79402-560x450-03.49fa2a7b001e506a.png',
        sale: false,
        sellCount: 15,
    },
    {
        id: 8,
        name: 'Lenovo Wireless Mouse',
        category: 'accesories',
        brand: 'Lenovo',
        price: 100,
        description: 'The Lenovo 300 Wireless Compact Mouse is designed to offer the best balance between mobility and function. The mouse features a 1000 dpi sensor, 3 buttons and a unique ergonomic contour to give you the freedom to create whenever and wherever. It boasts a 12-month battery life from a single AA battery and 10 million clicks lifecycle buttons to offer Super portable design.',
        img: 'https://p1-ofp.static.pub/ShareResource/560x450/SSNP/GX30K79402/GX30K79402-560x450-03.49fa2a7b001e506a.png',
        sale: false,
        sellCount: 15,
    },
    {
        id: 9,
        name: 'Galaxy smart-watch 12.56',
        category: 'smartwatches',
        brand: 'Samsung',
        price: 85,
        description: 'The Lenovo 300 Wireless Compact Mouse is designed to offer the best balance between mobility and function. The mouse features a 1000 dpi sensor, 3 buttons and a unique ergonomic contour to give you the freedom to create whenever and wherever. It boasts a 12-month battery life from a single AA battery and 10 million clicks lifecycle buttons to offer Super portable design.',
        img: 'https://d3m9l0v76dty0.cloudfront.net/system/photos/9868585/large/87dcc78e6805dd451d697722a83d707c.png',
        sale: true,
        sellCount: 15,
    },

];

export default data;