const data =[
    {
        id: 1,
        name: 'Lenovo Wireless Mouse',
        category: 'accesories',
        brand: 'Lenovo',
        price: 65,
        description: 'The Lenovo 300 Wireless Compact Mouse is designed to offer the best balance between mobility and function. The mouse features a 1000 dpi sensor, 3 buttons and a unique ergonomic contour to give you the freedom to create whenever and wherever. It boasts a 12-month battery life from a single AA battery and 10 million clicks lifecycle buttons to offer Super portable design.',
        img: 'https://p1-ofp.static.pub/ShareResource/560x450/SSNP/GX30K79402/GX30K79402-560x450-03.49fa2a7b001e506a.png',
        sale: false,
        sellCount: 15,
    },
    {
        id: 2,
        name: 'Lenovo Wireless Mouse',
        category: 'accesories',
        brand: 'Lenovo',
        price: 65,
        description: 'The Lenovo 300 Wireless Compact Mouse is designed to offer the best balance between mobility and function. The mouse features a 1000 dpi sensor, 3 buttons and a unique ergonomic contour to give you the freedom to create whenever and wherever. It boasts a 12-month battery life from a single AA battery and 10 million clicks lifecycle buttons to offer Super portable design.',
        img: 'https://p1-ofp.static.pub/ShareResource/560x450/SSNP/GX30K79402/GX30K79402-560x450-03.49fa2a7b001e506a.png',
        sale: false,
        sellCount: 15,
    },
    {
        id: 3,
        name: 'Lenovo Wireless Mouse',
        category: 'accesories',
        brand: 'Lenovo',
        price: 65,
        description: 'The Lenovo 300 Wireless Compact Mouse is designed to offer the best balance between mobility and function. The mouse features a 1000 dpi sensor, 3 buttons and a unique ergonomic contour to give you the freedom to create whenever and wherever. It boasts a 12-month battery life from a single AA battery and 10 million clicks lifecycle buttons to offer Super portable design.',
        img: 'https://p1-ofp.static.pub/ShareResource/560x450/SSNP/GX30K79402/GX30K79402-560x450-03.49fa2a7b001e506a.png',
        sale: false,
        sellCount: 15,
    },
    {
        id: 4,
        name: 'Lenovo Wireless Mouse',
        category: 'accesories',
        brand: 'Lenovo',
        price: 65,
        description: 'The Lenovo 300 Wireless Compact Mouse is designed to offer the best balance between mobility and function. The mouse features a 1000 dpi sensor, 3 buttons and a unique ergonomic contour to give you the freedom to create whenever and wherever. It boasts a 12-month battery life from a single AA battery and 10 million clicks lifecycle buttons to offer Super portable design.',
        img: 'https://p1-ofp.static.pub/ShareResource/560x450/SSNP/GX30K79402/GX30K79402-560x450-03.49fa2a7b001e506a.png',
        sale: false,
        sellCount: 15,
    },
    {
        id: 5,
        name: 'Lenovo Wireless Mouse',
        category: 'accesories',
        brand: 'Lenovo',
        price: 65,
        description: 'The Lenovo 300 Wireless Compact Mouse is designed to offer the best balance between mobility and function. The mouse features a 1000 dpi sensor, 3 buttons and a unique ergonomic contour to give you the freedom to create whenever and wherever. It boasts a 12-month battery life from a single AA battery and 10 million clicks lifecycle buttons to offer Super portable design.',
        img: 'https://p1-ofp.static.pub/ShareResource/560x450/SSNP/GX30K79402/GX30K79402-560x450-03.49fa2a7b001e506a.png',
        sale: false,
        sellCount: 15,
    },
    {
        id: 6,
        name: 'Lenovo Wireless Mouse',
        category: 'accesories',
        brand: 'Lenovo',
        price: 65,
        description: 'The Lenovo 300 Wireless Compact Mouse is designed to offer the best balance between mobility and function. The mouse features a 1000 dpi sensor, 3 buttons and a unique ergonomic contour to give you the freedom to create whenever and wherever. It boasts a 12-month battery life from a single AA battery and 10 million clicks lifecycle buttons to offer Super portable design.',
        img: 'https://p1-ofp.static.pub/ShareResource/560x450/SSNP/GX30K79402/GX30K79402-560x450-03.49fa2a7b001e506a.png',
        sale: false,
        sellCount: 15,
    },
    {
        id: 7,
        name: 'Lenovo Wireless Mouse',
        category: 'accesories',
        brand: 'Lenovo',
        price: 65,
        description: 'The Lenovo 300 Wireless Compact Mouse is designed to offer the best balance between mobility and function. The mouse features a 1000 dpi sensor, 3 buttons and a unique ergonomic contour to give you the freedom to create whenever and wherever. It boasts a 12-month battery life from a single AA battery and 10 million clicks lifecycle buttons to offer Super portable design.',
        img: 'https://p1-ofp.static.pub/ShareResource/560x450/SSNP/GX30K79402/GX30K79402-560x450-03.49fa2a7b001e506a.png',
        sale: false,
        sellCount: 15,
    },
    {
        id: 8,
        name: 'Lenovo Wireless Mouse',
        category: 'accesories',
        brand: 'Lenovo',
        price: 65,
        description: 'The Lenovo 300 Wireless Compact Mouse is designed to offer the best balance between mobility and function. The mouse features a 1000 dpi sensor, 3 buttons and a unique ergonomic contour to give you the freedom to create whenever and wherever. It boasts a 12-month battery life from a single AA battery and 10 million clicks lifecycle buttons to offer Super portable design.',
        img: 'https://p1-ofp.static.pub/ShareResource/560x450/SSNP/GX30K79402/GX30K79402-560x450-03.49fa2a7b001e506a.png',
        sale: false,
        sellCount: 15,
    },
    {
        id: 9,
        name: 'Lenovo Wireless Mouse',
        category: 'accesories',
        brand: 'Lenovo',
        price: 65,
        description: 'The Lenovo 300 Wireless Compact Mouse is designed to offer the best balance between mobility and function. The mouse features a 1000 dpi sensor, 3 buttons and a unique ergonomic contour to give you the freedom to create whenever and wherever. It boasts a 12-month battery life from a single AA battery and 10 million clicks lifecycle buttons to offer Super portable design.',
        img: 'https://p1-ofp.static.pub/ShareResource/560x450/SSNP/GX30K79402/GX30K79402-560x450-03.49fa2a7b001e506a.png',
        sale: false,
        sellCount: 15,
    },

];

export default data;